# Generated by Django 5.2.5 on 2026-01-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
