# Generated by Django 5.2.5 on 2026-01-04

from django.db import migrations, models


def populate_profile_slugs(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    profiles = Profile.objects.select_related("user").filter(
        models.Q(profile_slug__isnull=True) | models.Q(profile_slug="")
    )
    for profile in profiles:
        user = getattr(profile, "user", None)
        if not user:
            continue
        profile.profile_slug = user.username
        profile.save(update_fields=["profile_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_photo_profile_profile_slug"),
    ]

    operations = [
        migrations.RunPython(populate_profile_slugs, migrations.RunPython.noop),
    ]
